start python obs_stars_inFOV.py --Vmax 0 --theta_FOV 0
start python obs_stars_inFOV.py --Vmax 1 --theta_FOV 0
start python obs_stars_inFOV.py --Vmax 2 --theta_FOV 0
start python obs_stars_inFOV.py --Vmax 3 --theta_FOV 0
start python obs_stars_inFOV.py --Vmax 4 --theta_FOV 0
start python obs_stars_inFOV.py --Vmax 0 --theta_FOV 1
start python obs_stars_inFOV.py --Vmax 1 --theta_FOV 1
start python obs_stars_inFOV.py --Vmax 2 --theta_FOV 1
start python obs_stars_inFOV.py --Vmax 3 --theta_FOV 1
start python obs_stars_inFOV.py --Vmax 4 --theta_FOV 1
start python obs_stars_inFOV.py --Vmax 0 --theta_FOV 2
start python obs_stars_inFOV.py --Vmax 1 --theta_FOV 2
start python obs_stars_inFOV.py --Vmax 2 --theta_FOV 2
start python obs_stars_inFOV.py --Vmax 3 --theta_FOV 2
start python obs_stars_inFOV.py --Vmax 4 --theta_FOV 2
start python obs_stars_inFOV.py --Vmax 0 --theta_FOV 3
start python obs_stars_inFOV.py --Vmax 1 --theta_FOV 3
start python obs_stars_inFOV.py --Vmax 2 --theta_FOV 3
start python obs_stars_inFOV.py --Vmax 3 --theta_FOV 3
start python obs_stars_inFOV.py --Vmax 4 --theta_FOV 3
